### ISSUE TITLE
Players keep XP but drop XP on death, allowing for infinite XP

### ISSUE THREAD

**Issue by boreals-back-again** [Enderbyte-Programs/KeepChoice#1]
A player on my server found out he can keep dying over and over again to get infinite XP. You die and drop a little XP but you don't lose XP in your inventory.

config.yml:

```
default:
  # Specifies what should be the default behaviour.
  Enabled: true
# Should the player keep their items if they die? By default!

# You can specify specific settings for other worlds. See the example below:

exampleworld:
  Enabled: true

runinworlds:
- '*'
- __placeholder

# DO NOT EDIT THIS OBJECT - DATA STORAGE!!

data:
  __placeholder:
    empty: ''
  d96e37e7-8acd-4687-b5fd-8307b07ebac2:
    world: true
    world_the_end: false
    world_nether: false
  00000000-0000-0000-0009-01f19fe40998:
    world: true
    world_the_end: true
    world_nether: true
  00000000-0000-0000-0009-01f474271c16:
    world: true
    world_the_end: true
    world_nether: true
  00000000-0000-0000-0009-01ffd234a120:
    world: true
    world_the_end: true
    world_nether: true
  00000000-0000-0000-0009-01f1ab5c4ce1:
    world: true
    world_the_end: true
    world_nether: true
  00000000-0000-0000-0009-01f6d420a790:
    world: true
    world_the_end: true
    world_nether: true
  00000000-0000-0000-0009-01fc6276a3ec:
    world: true
    world_the_end: true
    world_nether: true
  0a5ca7fb-376b-4725-a287-e7a940a2ea5d:
    world: true
    world_the_end: true
    world_nether: true
  00000000-0000-0000-0009-01fbd809673e:
    world: true
    world_the_end: true
    world_nether: true

# YOU MAY EDIT AGAIN

```
